# Generated by Django 3.2.4 on 2021-08-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20210826_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='preperation_time',
            new_name='preparation_time',
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
